movies/movie/urls.py
from django.conf.urls import url
from . import views

app_name = 'movie'
urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^main/$',views.index, name='index'),
    url(r'^register_handler/$', views.register_handler, name='register_handler'),
    url(r'^user_Authenticate/$', views.user_Authenticate, name='user_Authenticate'),
    url(r'^create_database/$', views.create_database, name='create_database'),
    url(r'^adminPage/$', views.adminPage, name='adminPage'),
    url(r'^myprofile/index.html/$', views.profile, name='profile'),
    url(r'^myprofile/form.html/$', views.profiel_form, name='profiel_form'),
    url(r'^country/$', views.country, name='country'),
    url(r'^add_country/$', views.add_country, name='add_country'),
    url(r'^update_country/$', views.update_country, name='update_country'),
    url(r'^delete_country/$', views.delete_country, name='delete_country'),
    url(r'^director/$', views.director, name='director'),
    url(r'^add_director/$', views.add_director, name='add_director'),
    url(r'^delete_director/$', views.delete_director, name='delete_director'),
    url(r'^movie/$', views.movie, name='movie'),
    url(r'^add_movie/$', views.add_movie, name='add_movie'),
    url(r'^delete_movie/$', views.delete_movie, name='delete_movie'),
    url(r'^create_db_info/$', views.create_db_info, name='create_db_info'),
    url(r'^request/$', views.send_request, name='request'),
    url(r'^verify/$', views.verify , name='verify'),
    url(r'^show_info/(?P<user_name>.*)/$', views.show_info , name='show_info'),
]

movies/movies/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('movie.urls')),
    url(r'^admin/', admin.site.urls),
]

movies/movie/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

movies/movie/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from . import connection
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login
from django.http import HttpResponse
from django.shortcuts import redirect
from zeep import Client
import jdatetime



try:
    client = connection.Connection('root', 'root', '0.0.0.0', 6543)
except:
    pass


# Create your views here..
# process on sign up page and return alert and rediret
def register_handler(request):
    global client
    fname=request.POST.get('firstname', False)
    lname=request.POST.get('lastname', False)
    email=request.POST.get('email', False)
    username = request.POST.get('username', False)
    password = request.POST.get('pass', False)
    password_repeat = request.POST.get('pass-repeat', False)
    if password == password_repeat:
        if username and password:
            client.create_user(username, password)
            User.objects.create_user(first_name=fname,last_name=lname,email=email,username=username, password=password,)
            messages.success(request, 'Your registration has been successfully completed')
        else:
            messages.error(request, 'Registration was encountered error')
    else:
        messages.warning(request, 'your password is not equal')

    return HttpResponseRedirect(reverse('movie:login'))


# render login page
def login(request):
    return render(request, 'movie/login.html', {})


# process on login page and redirect
def user_Authenticate(request):
    username = request.POST.get('uname', False)
    password = request.POST.get('psw', False)
    if username and password =='admin':
        return HttpResponseRedirect(reverse('movie:adminPage'))
    else:
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return HttpResponseRedirect(reverse('movie:profile'))

        else:
            messages.error(request, 'Your account is not logged in. Please register')
            return HttpResponseRedirect(reverse('movie:login'))


# render index.html file
def profile(request):
    global client
    now_date=jdatetime.date.today().strftime("%d /%m /%Y")
    top_name = request.user.username
    db_user = client.return_user_dbs(top_name)
    chart_items = client.chart_doughnut(top_name)
    if db_user == 'false':
        no_dbs = 'There are no databases'
    else:
        no_dbs = 'not null'
    Percentage = []
    if chart_items[0][0]!=None:
        if chart_items[0][4]==0:
            chart_items[0][4]=1

        for i in range(0, len(chart_items[0])-1):
            Percentage.append(round((chart_items[0][i] * 100) / chart_items[0][4], 2))
    total_cost=0
    if db_user=='false':
        total_cost=0
    else:
        for i in db_user:
            total_cost+=i[6]
    return render(request, 'gentelella/index.html',
                  {'top_name': top_name, 'db_user': db_user, 'no_dbs': no_dbs, 'chart_items': chart_items[0],
                   'Percentage': Percentage,'now_date':now_date,'total_cost':total_cost})


# render form.html file
def profiel_form(request):
    global client
    now_date=jdatetime.date.today().strftime("%d /%m /%Y")
    top_name = request.user.username
    database_name = request.POST.get('db_name', False)
    if database_name:
        db = top_name + "_" + database_name
        client.insert_db_info(top_name, db)
        client.create_database(db)
        return HttpResponseRedirect(reverse('movie:profiel_form'))

    db_user = client.return_user_dbs(top_name)
    return render(request, 'gentelella/form.html', {'top_name': top_name, 'db_user': db_user,'now_date':now_date})


def create_db_info(request):
    global client
    client.create_db_info()
    return HttpResponse('Done')


def send_request(request):
    global client
    db_user = client.return_user_dbs(request.user.username)
    total_cost=0
    if db_user=='false':
        total_cost=0
    else:
        for i in db_user:
            total_cost+=i[6]
    MERCHANT = '00000000-0000-0000-0000-000000000000'
    client1 = Client('https://sandbox.zarinpal.com/pg/services/WebGate/wsdl')
    amount = total_cost  # Toman / Required
    description = "تراکنش استفاده از سیستم دیتابیس به عنوان خدمت ابری"# Required
    email = 'DBAS@db.ir'  # Optional
    mobile = '09123456789'  # Optional
    CallbackURL = 'http://93.118.97.199:8085/verify/' # Important: need to edit for realy server.
    result = client1.service.PaymentRequest(MERCHANT, amount, description, email, mobile, CallbackURL)
    if result.Status == 100:
        return redirect('https://sandbox.zarinpal.com/pg/StartPay/' + str(result.Authority))
    else:
        return HttpResponse('Error code: ' + str(result.Status))



def verify(request):
    global client
    myUser=request.user.username
    db_user = client.return_user_dbs(myUser)
    total_cost=0
    if db_user=='false':
        total_cost=0
    else:
        for i in db_user:
            total_cost+=i[6]
    MERCHANT = '00000000-0000-0000-0000-000000000000'
    client1 = Client('https://sandbox.zarinpal.com/pg/services/WebGate/wsdl')
    amount = total_cost  # Toman / Required
    if request.GET.get('Status') == 'OK':
        result = client1.service.PaymentVerification(MERCHANT, request.GET['Authority'], amount)
        if result.Status == 100:
            client.payment_action(myUser)
            # return HttpResponse('Transaction success.\nRefID: ' + str(result.RefID))

            return HttpResponseRedirect(reverse('movie:profile'))
        elif result.Status == 101:
            return HttpResponse('Transaction submitted : ' + str(result.Status))
        else:
            return HttpResponse('Transaction failed.\nStatus: ' + str(result.Status))
    else:
        return HttpResponse('Transaction failed or canceled by user')



def adminPage(request):
    now_date=jdatetime.date.today().strftime("%d /%m /%Y")
    users=User.objects.all()
    # usernames = User.objects.values_list('email', flat=True)
    for i in users:
        print (i.email)
    return render(request,'gentelella/tables.html',{'now_date':now_date,'users':users})

def show_info(request,user_name):
    global client
    now_date=jdatetime.date.today().strftime("%d /%m /%Y")
    db_user = client.return_user_dbs(user_name)
    chart_items = client.chart_doughnut(user_name)
    if db_user == 'false':
        no_dbs = 'There are no databases'
    else:
        no_dbs = 'not null'
    Percentage = []
    if chart_items[0][0]!=None:
        if chart_items[0][4]==0:
            chart_items[0][4]=1

        for i in range(0, len(chart_items[0])-1):
            Percentage.append(round((chart_items[0][i] * 100) / chart_items[0][4], 2))
    total_cost=0
    if db_user=='false':
        total_cost=0
    else:
        for i in db_user:
            total_cost+=i[6]
    return render(request, 'gentelella/index.html',
                  {'top_name': user_name, 'db_user': db_user, 'no_dbs': no_dbs, 'chart_items': chart_items[0],
                   'Percentage': Percentage,'now_date':now_date,'total_cost':total_cost})






def create_database(request):
    global client
    # client.create_database('nano')
    client.use_database('sajjad_userInfo')
    client.create_table('j', {'id': 'int', 'name': 'text'}, ['id'])
    # client.create_table('jamali', {'id': 'int', 'first_name': 'text', 'last_name': 'text', 'date_of_birth': 'text'},
    #                     ['id'])
    # client.create_table('jamshidi',
    #                     {'id': 'int', 'name': 'text', 'director_id': 'int', 'country_id': 'int', 'year': 'text',
    #                      'description': 'text'}, ['id'])
    return HttpResponse('Done')

def index(request):
    global client
    client.use_database('movie')
    movie_table = client.table('movie')
    movies = movie_table.get_item()

    country_table = client.table('country')
    countries = country_table.get_item()

    director_table = client.table('director')
    directors = director_table.get_item()

    for i in range(0, len(movies)):
        for country in countries:
            if int(country['id']) == int(movies[i]['country_id']):
                movies[i]['country_name'] = country['name']
        for director in directors:
            if int(director['id']) == int(movies[i]['director_id']):
                movies[i]['director_name'] = director['first_name'] + " " + director['last_name']
    return render(request, 'movie/index.html', {'movies': movies})


def country(request):
    global client
    client.use_database('jamshidi_reza_salam')
    table = client.table('ahmadi')
    rows = table.get_item()
    return render(request, 'movie/country.html', {'rows': rows})


def add_country(request):
    global client
    client.use_database('jamshidi_reza_salam')
    # client.use_database('movie')
    table = client.table('ahmadi')
    id = request.POST['id']
    name = request.POST['name']
    table.put_item({'id': int(id), 'name': name})
    return HttpResponseRedirect(reverse('movie:country'))


def update_country(request):
    global client
    client.use_database('jamshidi_reza_salam')
    table = client.table('ahmadi')
    id = request.POST['id']
    name = request.POST['name']
    table.update_item({'name': name}, {'id': int(id)})
    return HttpResponseRedirect(reverse('movie:country'))


def delete_country(request):
    global client
    client.use_database('jamshidi_reza_salam')
    table = client.table('ahmadi')
    id = request.GET['id']
    table.delete_item({'id': int(id)})
    return HttpResponseRedirect(reverse('movie:country'))


def director(request):
    global client
    client.use_database('movie')
    table = client.table('director')
    rows = table.get_item()
    return render(request, 'movie/director.html', {'rows': rows})


def add_director(request):

movies/movie/templates/movie/country.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Country</title>
        {% load static %}
        <link rel="stylesheet"  href="{% static 'movie/country.css' %}"/>
    </head>
    <body>
        <h1>Country</h1>
        <table>
            <thead>
                <tr>
                    <td>id</td>
                    <td>Name</td>
                    <td>Delete</td>
                </tr>
            </thead>
            <tbody>
                {% for row in rows %}
                    <tr>
                        <td>{{ row.id }}</td>
                        <td>{{ row.name }}</td>
                        <td><a href="{% url 'movie:delete_country' %}?id={{ row.id }}">delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table><br />
        <form action="{% url 'movie:add_country' %}" method="post">
            {% csrf_token %}
            <input type="text" name="id" placeholder="id" /><br />
            <input type="text" name="name" placeholder="Country Name" /><br />
            <input type="submit" value="Add" />
        </form>
        <br />
        <form action="{% url 'movie:update_country' %}" method="post">
            {% csrf_token %}
            <input type="text" name="id" placeholder="id" /><br />
            <input type="text" name="name" placeholder="Country Name" /><br />
            <input type="submit" value="Edit" />
        </form>

    </body>
</html>

movies/movie/templates/movie/director.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Director</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'movie/country.css' %}"/>
    </head>
    <body>
        <h1>Director</h1>
        <table>
            <thead>
                <tr>
                    <td>id</td>
                    <td>First Name</td>
                    <td>Last Name</td>
                    <td>Date of Birth</td>
                    <td>Delete</td>
                </tr>
            </thead>
            <tbody>
                {% for row in rows %}
                    <tr>
                        <td>{{ row.id }}</td>
                        <td>{{ row.first_name }}</td>
                        <td>{{ row.last_name }}</td>
                        <td>{{ row.date_of_birth }}</td>
                        <td><a href="{% url 'movie:delete_director' %}?id={{ row.id }}">delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table><br />
        <form action="{% url 'movie:add_director' %}" method="post">
            {% csrf_token %}
            <input type="text" name="id" placeholder="id" /><br />
            <input type="text" name="first_name" placeholder="First Name" /><br />
            <input type="text" name="last_name" placeholder="Last Name" /><br />
            <input type="text" name="date_of_birth" placeholder="Date of Birth" /><br />
            <input type="submit" value="Add" />
        </form>
    </body>
</html>

movies/movie/templates/movie/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Home Page</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'movie/country.css' %}"/>
    </head>
    <body>
        <h1>Welcome</h1>
        <a href="{% url 'movie:country' %}">Country</a>
        <br />
        <a href="{% url 'movie:director' %}">Director</a>
        <br />
        <a href="{% url 'movie:movie' %}">Movie</a>
        <table>
            <thead>
                <tr>
                    <td>id</td>
                    <td>Name</td>
                    <td>Director</td>
                    <td>Country</td>
                    <td>Year</td>
                    <td>Description</td>
                </tr>
            </thead>
            <tbody>
                {% for movie in movies %}
                    <tr>
                        <td>{{ movie.id }}</td>
                        <td>{{ movie.name }}</td>
                        <td>{{ movie.director_name }}</td>
                        <td>{{ movie.country_name }}</td>
                        <td>{{ movie.year }}</td>
                        <td>{{ movie.description }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table><br />
    </body>
</html>

movies/movie/templates/movie/login.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}"/>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script>

        $(window).ready(function () {
            setTimeout(function () {
                $('#alert').slideUp(1000);
            }, 4000);

        });
        function showing_pass() {
            var temp = document.getElementById("show_pass");
            if (temp.type === "password") {
                temp.type = "text";
            } else {
                temp.type = "password"
            }
        }


        var modal = document.getElementById('id01');
        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>


</head>
<body id="main">
{% if messages %}
<ul id="alert" class="messages">
    {% for message in messages %}
    <li
            {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

<h2>DataBase As Service
    <span id="logo"></span>
</h2>


<form action="{% url 'movie:user_Authenticate' %}" method="post">
    {% csrf_token %}
    <div class="imgcontainer">
        <h4>Login Form</h4>
    </div>

    <div class="container">
        <label><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" required>

        <label><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required id="show_pass">

        <button type="submit">Login<span id="login_logo"></span></button>
        <input type="checkbox" onclick="showing_pass()">Show Password
        <label>
            <input type="checkbox" checked="checked" name="remember"> Remember me
        </label>
    </div>

    <button onclick="document.getElementById('id01').style.display='block'"
            style="font-size: 1em;width:auto;margin-left: 18px;">Sign Up
    </button>
</form>


<div id="id01" class="modal">
    <span onclick="document.getElementById('id01').style.display='none'" class="close"
          title="Close Modal">&times;</span>
    <form class="modal-content" method="post" action="{% url 'movie:register_handler' %}">
        {% csrf_token %}
        <div class="container">
            <h1>Sign Up</h1>
            <p>Please fill in this form to create an account.</p>
            <hr>
            <label><b>Firstname</b></label>
            <input type="text" placeholder="Enter Firstname" name="firstname">

            <label><b>Lastname</b></label>
            <input type="text" placeholder="Enter Lastname" name="lastname">

            <label><b>Email</b></label>
            <input type="text" placeholder="Enter Email" name="email">

            <label><b>Username</b></label>
            <input type="text" placeholder="Enter Username" name="username">

            <label><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="pass">

            <label><b>Repeat Password</b></label>
            <input type="password" placeholder="Repeat Password" name="pass-repeat" >
            <input type="checkbox" onclick=myFunction()>Show Password

            <div class="clearfix">
                <button id="submit_button" type="submit" class="signupbtn">Sign Up</button>
            </div>
        </div>
    </form>

</div>


</body>
</html>

movies/movie/templates/movie/movie.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Movie</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'movie/country.css' %}">
    </head>
    <body>
        <h1>Movie</h1>
        <table>
            <thead>
                <tr>
                    <td>id</td>
                    <td>Name</td>
                    <td>Director_ID</td>
                    <td>Country_ID</td>
                    <td>Year</td>
                    <td>Description</td>
                    <td>Delete</td>
                </tr>
            </thead>
            <tbody>
                {% for row in rows %}
                    <tr>
                        <td>{{ row.id }}</td>
                        <td>{{ row.name }}</td>
                        <td>{{ row.director_id }}</td>
                        <td>{{ row.country_id }}</td>
                        <td>{{ row.year }}</td>
                        <td>{{ row.description }}</td>
                        <td><a href="{% url 'movie:delete_movie' %}?id={{ row.id }}">delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table><br />
        <form action="{% url 'movie:add_movie' %}" method="post">
            {% csrf_token %}
            <input type="text" name="id" placeholder="id" /><br />
            <input type="text" name="name" placeholder="Name" /><br />
            Director : <select name="director_id">
                {% for director in directors %}
                    <option value="{{ director.id }}">{{ director.id }} : {{ director.first_name }} {{ director.last_name }}</option>
                {% endfor %}
            </select>
            <br />
            Country : <select name="country_id">
                {% for country in countries %}
                    <option value="{{ country.id }}">{{ country.id }} : {{ country.name }}</option>
                {% endfor %}
            </select>
            <br />
            <input type="text" name="year" placeholder="Year" /><br />
            <textarea name="description" placeholder="Description ..."></textarea><br />
            <input type="submit" value="Add" />
        </form>
    </body>
</html>